# Generated by Django 5.1.2 on 2024-10-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='plants/')),
                ('light_requirement', models.CharField(choices=[('LOW', 'Faible luminosité'), ('MEDIUM', 'Luminosité moyenne'), ('HIGH', 'Forte luminosité')], default='MEDIUM', max_length=6)),
                ('maintenance_level', models.CharField(choices=[('LOW', 'Facile'), ('MEDIUM', 'Moyen'), ('HIGH', 'Exigeant')], default='LOW', max_length=6)),
                ('watering_frequency', models.IntegerField(help_text='Nombre de jours entre les arrosages')),
                ('ideal_temperature', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_type', models.CharField(choices=[('BALCONY', 'Balcon'), ('TERRACE', 'Terrasse'), ('WINDOWSILL', 'Rebord de fenêtre')], max_length=10)),
                ('light_level', models.CharField(choices=[('LOW', 'Faible luminosité'), ('MEDIUM', 'Luminosité moyenne'), ('HIGH', 'Forte luminosité')], max_length=6)),
                ('maintenance_time', models.IntegerField(help_text='Minutes par semaine')),
                ('experience_level', models.CharField(choices=[('BEGINNER', 'Débutant'), ('INTERMEDIATE', 'Intermédiaire'), ('EXPERT', 'Expert')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
