# Generated by Django 5.1.2 on 2024-10-26 13:11

import plants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/', validators=[plants.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='space_type',
            field=models.CharField(choices=[('BALCONY', 'Balcon'), ('TERRACE', 'Terrasse'), ('WINDOWSILL', 'Rebord de fenêtre')], max_length=15),
        ),
    ]
